### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by LunaSquee** [BennyQBD/3DEngineCpp#19]
Some weird issue occurs when I run this. I have followed the build instructions and when I run, all I see is a black screen.

When I back up a little bit(S key) I see this
![image](https://cloud.githubusercontent.com/assets/6363179/3488813/37085558-0505-11e4-892e-0c699c8ad75f.png)
And when I back up even more, this shows up 
![image](https://cloud.githubusercontent.com/assets/6363179/3488814/433d3cc6-0505-11e4-8229-f9a7e4a5d350.png)

I'm on Windows 7 (32 bit), using Visual Studio Express 2013
OpenGL version (according to graphics card) is 6.14.10.12874

**Comment by PseudoFreak** [comment]
That is weird. The OpenGL version doesn't really make sense...
Is that the newest version of the engine? You changed nothing (especially with the resources in the res folder)? If you could post a video, that would be great.

**Comment by pythoneer** [comment]
That is some internal implementation number from the Catalyst 14.4 driver i guess. That should result in OpenGL 4.4 ... But i can't reproduce this. But what confuses me is the fact that i've seen something like the second screenshot recently, but i don't know the context anymore. It could be, that i checked out to different commits on the repo and forgot to fully rebuild ... but i can't recall where i've seen that artifacts. @LunaSquee can you make a full rebuild/clean or checkout/clone the repo again in a separate folder and build?

**Comment by LunaSquee** [comment]
This keeps happening no matter what I do.
No, I don't change anything, I just clone the repo and follow the build instructions.
Also, is it normal to have like 16045 warnings in "Error List" when the build finishes?

**Comment by pythoneer** [comment]
Ok it was just a guess from my side. I can only speak for my System (ArchLinux gcc) that i get a few warnings but not as much as you. What about checkout an earlier version of the code?

**Comment by LunaSquee** [comment]
I even tried using CodeBlocks, but I got an error on window.ccp "error: fprintf was not declared in this scope" and "error: stderr was not declared in this scope"

**Comment by LunaSquee** [comment]
Doesn't look like I can get this to work..

**Comment by pythoneer** [comment]
What about earlier versions?

**Comment by LunaSquee** [comment]
"Included Basic Profiling Tools" is the last commit that works

**Comment by zeyorama** [comment]
The prototype for fprintf is declared in stdio.h. stderr is in stdlib.h or also in stdio.h. Look for your includes.
One tip: look for the letter cases, vs compiler is non case-sensitive, but under Unix Systems, gcc for example isn't.

Hope it helps.

**Comment by ghost** [comment]
I have the same graphical bug. 

On the latest version you can change renderingEngine.cpp line 43 to
m_defaultShader("basicShader"),

After that the scene will load fine but without any fancy lighting or shadows. So it looks like this is a shader issue somewhere in the "Experimental Shading system" commit.

Windows 7 (64bit), ATI 7970, Catalyst 14.4, The engine is setting glsl version 320, I tried setting different version manually in shader.cpp and those fail to compile or give the same result ... (shader newbie)

Edit: The same happens when I build on Linux, ATI 7970, Driver 13.35.1005

**Comment by BennyQBD** [comment]
Wait, the engine is setting GLSL version 320? If so, there's a very good chance that's the issue. 

At around line 65 in shader.cpp, there's an if statement which should be reading in your OpenGL version as 320, and then converting that to 150. I can't reproduce this issue on my system, but if you can play around with that and see if there's something wrong with that conversion system, that might fix the issue.

**Comment by LunaSquee** [comment]
What exactly am I supposed to change? When I change the s_glslVersion to anything else I get "Cannot find or open the PDB file."

**Comment by BennyQBD** [comment]
Scratch that, I think I've found the issue.

I made a completely bone-headed mistake with identifying attributes in the new shader system. For some reason I was thinking the preprocessor ran before attributes are added, when in actuality it's the other way around. As a result, all the attributes added were complete garbage strings. Frankly, I'm surprised the code worked for anyone at all.

Try now. It might not have fixed this specific issue, but I'm certain it's fixed some issues.

**Comment by LunaSquee** [comment]
It appears to be working now, I see the terrain and the fancy shadows and stuff.

**Comment by BennyQBD** [comment]
That's great! If this has solved the issue for anyone else, let me know so we can confirm the issue is actually solved.

Otherwise, if no one else is still encountering the issue, I think it's safe to close this.

**Comment by ghost** [comment]
The problem is fixed on my end as well.
(Clean build no issues)

**Comment by BennyQBD** [comment]
Since I've heard no further reports of this issue in the past week, I think it's safe to say this issue is fixed. Closing.
